### PR TITLE
Support ADDL and II

### PR DESCRIPTION
**Pull request by mhovd**
Adds support for ADDL and II in the datafile. Negative ADDL will give past doses, positive values will give future doses.

PS: This intentionally removes the previous ADDL and II from the bimodal_ke dataset, as this has been used for testing of the crate.

### CODE REVIEW

**Comment by mhovd** [comment]
@mnneely and @Siel, what do you think of the following suggested changes to how ADDL works?

- ADDL can be positive or negative
- Negative values will give "past doses", i.e. time of dose(s) will be ADLL * II, and the sign will be respected. All observations are then shifted in time to account for this, e.g. for EVID = 1, TIME = 0, ADDL = -10, II = 12, the first dose is given at TIME = -120. As such, all observations and following events are shifted by 120 hours. As such, EVID = 0, TIME = 10 -> TIME = 130.
- Positive values of ADDL will give "future doses", and will not shift any observations.
- ADDL = -1 will now be exactly that, and not default to 100 past doses. I think this is more transparent and flexible than the previous implementation.

Here is an example 
| ID | EVID | TIME | DUR | DOSE | ADDL | II | INPUT | OUT | OUTEQ | C0 | C1 | C2 | C3 |
|----|------|------|-----|------|------|----|-------|-----|-------|----|----|----|----|
| 1  | 1    | 0    | 0   | 600  | -10  | 12 | 1     | .   | .     | .  | .  | .  | .  |
| 1  | 0    | 9    | .   | .    | .    | .  | .     | 100 | 100   | .  | .  | .  | .  |
| 2  | 1    | 0    | 0   | 600  | 10   | 12 | 1     | .   | .     | .  | .  | .  | .  |
| 2  | 0    | 9    | .   | .    | .    | .  | .     | 100 | 100   | .  | .  | .  | .  |


| Subject | 0.0 | 9.0 | 12.0 | 24.0 | 36.0 | 48.0 | 60.0 | 72.0 | 84.0 | 96.0 | 108.0 | 120.0 | 129.0 |
|---------|-----|-----|------|------|------|------|------|------|------|------|-------|-------|-------|
| 1       | Dose| - | Dose | Dose | Dose | Dose | Dose | Dose | Dose | Dose | Dose  | Dose  | Observation |
| 2       | Dose| Observation| Dose | Dose | Dose | Dose | Dose | Dose | Dose | Dose | Dose  | Dose  | - |

**Comment by mhovd** [comment]
For the negative ADDLs, Anders also believes that the times should be "reset", i.e. all times should be shifted by ADDL * II, so that the observation time is not shifted, i.e. in the first example, the observation will still be at 9 hours.

@mnneely, thoughts?

**Comment by mnneely** [comment]
I don’t have a problem with ADDL = -x to mean give x doses in the past. Currently, the system is initialized with the amounts in each compartment at time 0 equal to the amounts at II hours after the 100th dose, I.e. a trough concentration after the 100th dose. There is no dose actually given at time 0. The motivation for all this was to capture the scenario when a patient or study subject was taking a drug, came into the clinic, had a sample drawn, and then consumed a witnessed dose. 

If, for example, a patient was taking (theoretically) a medication every 12 hours, and came in for a sample 5 hours after the last “steady state” dose, the data file would have ADDL = -1, II = 12 at time 0, another dose at time 0.01 (or some other low value), and the sample at time 5.

I think the logic would be better to have the compartment amounts be initialized at time 0 the same way, but a dose at time 0 given, so that the concentrations will rise from the trough after time 0, reflecting this additional dose.

Any times after ADDL = -x should be as recorded, e.g. a TIME = 9 in your scenario should be 129 “under the hood”. We should not allow observations in the past. This will also maintain compatibility with absolute date/time specification. 

Integrating ADDL = -x with EVID = 4 is always a bit tricky in my mind. I don’t know how NPCORE is handling EVID = 4. Are you treating each block (defined by EVID = 4) separately so that a user could specify prior doses for each block using ADDL = -x?

**Comment by mhovd** [comment]
> Any times after ADDL = -x should be as recorded, e.g. a TIME = 9 in your scenario should be 129 “under the hood”. We should not allow observations in the past. This will also maintain compatibility with absolute date/time specification.

I agree with this and your other notes! And I think it makes sense to compute the state at that time, and use that for TIME = 0.

> Integrating ADDL = -x with EVID = 4 is always a bit tricky in my mind. I don’t know how NPCORE is handling EVID = 4. Are you treating each block (defined by EVID = 4) separately so that a user could specify prior doses for each block using ADDL = -x?

Currently we don't, but what we are planning would support this. Basically, each block (incremented on EVID = 4) would be treated as a pseudo-individual. But the collection of their observations and predictions are used for calculating the likelihood of each support point, so all the data is used. I don't think this would be too complicated to implement.

**Pull request closed without merging**
